# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialogFastText.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FastTextDialog(object):
    def setupUi(self, FastTextDialog):
        FastTextDialog.setObjectName("FastTextDialog")
        FastTextDialog.resize(658, 706)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(FastTextDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(FastTextDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.modelCreatorTab = QtWidgets.QWidget()
        self.modelCreatorTab.setObjectName("modelCreatorTab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.modelCreatorTab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.createMainVLayout = QtWidgets.QVBoxLayout()
        self.createMainVLayout.setObjectName("createMainVLayout")
        self.configVLayout = QtWidgets.QVBoxLayout()
        self.configVLayout.setObjectName("configVLayout")
        self.FastTextConfigGBox = QtWidgets.QGroupBox(self.modelCreatorTab)
        self.FastTextConfigGBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FastTextConfigGBox.sizePolicy().hasHeightForWidth())
        self.FastTextConfigGBox.setSizePolicy(sizePolicy)
        self.FastTextConfigGBox.setMinimumSize(QtCore.QSize(300, 100))
        self.FastTextConfigGBox.setObjectName("FastTextConfigGBox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.FastTextConfigGBox)
        self.verticalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_8.setContentsMargins(9, 8, -1, -1)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.filePathHLayout = QtWidgets.QHBoxLayout()
        self.filePathHLayout.setObjectName("filePathHLayout")
        self.selectAnotherPathBtn = QtWidgets.QPushButton(self.FastTextConfigGBox)
        self.selectAnotherPathBtn.setObjectName("selectAnotherPathBtn")
        self.filePathHLayout.addWidget(self.selectAnotherPathBtn, 0, QtCore.Qt.AlignLeft)
        self.filePathLbl = QtWidgets.QLabel(self.FastTextConfigGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filePathLbl.sizePolicy().hasHeightForWidth())
        self.filePathLbl.setSizePolicy(sizePolicy)
        self.filePathLbl.setObjectName("filePathLbl")
        self.filePathHLayout.addWidget(self.filePathLbl, 0, QtCore.Qt.AlignHCenter)
        self.filePathField = QtWidgets.QLineEdit(self.FastTextConfigGBox)
        self.filePathField.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filePathField.sizePolicy().hasHeightForWidth())
        self.filePathField.setSizePolicy(sizePolicy)
        self.filePathField.setMinimumSize(QtCore.QSize(0, 0))
        self.filePathField.setMaximumSize(QtCore.QSize(220, 63))
        self.filePathField.setReadOnly(True)
        self.filePathField.setObjectName("filePathField")
        self.filePathHLayout.addWidget(self.filePathField)
        self.verticalLayout_8.addLayout(self.filePathHLayout)
        self.wordFrequencyHLayout = QtWidgets.QHBoxLayout()
        self.wordFrequencyHLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.wordFrequencyHLayout.setObjectName("wordFrequencyHLayout")
        self.wordFrequencyLbl = QtWidgets.QLabel(self.FastTextConfigGBox)
        self.wordFrequencyLbl.setObjectName("wordFrequencyLbl")
        self.wordFrequencyHLayout.addWidget(self.wordFrequencyLbl)
        self.wordFrequencyField = QtWidgets.QSpinBox(self.FastTextConfigGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wordFrequencyField.sizePolicy().hasHeightForWidth())
        self.wordFrequencyField.setSizePolicy(sizePolicy)
        self.wordFrequencyField.setMaximumSize(QtCore.QSize(110, 16777215))
        self.wordFrequencyField.setMinimum(1)
        self.wordFrequencyField.setMaximum(150)
        self.wordFrequencyField.setProperty("value", 5)
        self.wordFrequencyField.setObjectName("wordFrequencyField")
        self.wordFrequencyHLayout.addWidget(self.wordFrequencyField)
        self.verticalLayout_8.addLayout(self.wordFrequencyHLayout)
        self.vectorSizeHLayout = QtWidgets.QHBoxLayout()
        self.vectorSizeHLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.vectorSizeHLayout.setObjectName("vectorSizeHLayout")
        self.vectorSizeLbl = QtWidgets.QLabel(self.FastTextConfigGBox)
        self.vectorSizeLbl.setObjectName("vectorSizeLbl")
        self.vectorSizeHLayout.addWidget(self.vectorSizeLbl)
        self.vectorSizeField = QtWidgets.QSpinBox(self.FastTextConfigGBox)
        self.vectorSizeField.setMaximumSize(QtCore.QSize(110, 16777215))
        self.vectorSizeField.setMinimum(1)
        self.vectorSizeField.setMaximum(100000)
        self.vectorSizeField.setProperty("value", 100)
        self.vectorSizeField.setObjectName("vectorSizeField")
        self.vectorSizeHLayout.addWidget(self.vectorSizeField)
        self.verticalLayout_8.addLayout(self.vectorSizeHLayout)
        self.trainingSpeedHLayout = QtWidgets.QHBoxLayout()
        self.trainingSpeedHLayout.setObjectName("trainingSpeedHLayout")
        self.trainingSpeedLbl = QtWidgets.QLabel(self.FastTextConfigGBox)
        self.trainingSpeedLbl.setObjectName("trainingSpeedLbl")
        self.trainingSpeedHLayout.addWidget(self.trainingSpeedLbl)
        self.trainingSpeedField = QtWidgets.QDoubleSpinBox(self.FastTextConfigGBox)
        self.trainingSpeedField.setMaximumSize(QtCore.QSize(110, 16777215))
        self.trainingSpeedField.setDecimals(3)
        self.trainingSpeedField.setMinimum(0.001)
        self.trainingSpeedField.setMaximum(1.0)
        self.trainingSpeedField.setProperty("value", 0.025)
        self.trainingSpeedField.setObjectName("trainingSpeedField")
        self.trainingSpeedHLayout.addWidget(self.trainingSpeedField)
        self.verticalLayout_8.addLayout(self.trainingSpeedHLayout)
        self.windowHLayout = QtWidgets.QHBoxLayout()
        self.windowHLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.windowHLayout.setObjectName("windowHLayout")
        self.windowLbl = QtWidgets.QLabel(self.FastTextConfigGBox)
        self.windowLbl.setMinimumSize(QtCore.QSize(155, 20))
        self.windowLbl.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.windowLbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.windowLbl.setObjectName("windowLbl")
        self.windowHLayout.addWidget(self.windowLbl)
        self.windowField = QtWidgets.QSpinBox(self.FastTextConfigGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.windowField.sizePolicy().hasHeightForWidth())
        self.windowField.setSizePolicy(sizePolicy)
        self.windowField.setMaximumSize(QtCore.QSize(110, 16777215))
        self.windowField.setMinimum(1)
        self.windowField.setMaximum(150)
        self.windowField.setProperty("value", 5)
        self.windowField.setObjectName("windowField")
        self.windowHLayout.addWidget(self.windowField)
        self.verticalLayout_8.addLayout(self.windowHLayout)
        self.epochNumberHLayout = QtWidgets.QHBoxLayout()
        self.epochNumberHLayout.setObjectName("epochNumberHLayout")
        self.epochNumberLbl = QtWidgets.QLabel(self.FastTextConfigGBox)
        self.epochNumberLbl.setObjectName("epochNumberLbl")
        self.epochNumberHLayout.addWidget(self.epochNumberLbl)
        self.epochNumberField = QtWidgets.QSpinBox(self.FastTextConfigGBox)
        self.epochNumberField.setMaximumSize(QtCore.QSize(110, 16777215))
        self.epochNumberField.setMinimum(1)
        self.epochNumberField.setMaximum(1000)
        self.epochNumberField.setProperty("value", 5)
        self.epochNumberField.setObjectName("epochNumberField")
        self.epochNumberHLayout.addWidget(self.epochNumberField)
        self.verticalLayout_8.addLayout(self.epochNumberHLayout)
        self.nounOnlyHLayout = QtWidgets.QHBoxLayout()
        self.nounOnlyHLayout.setObjectName("nounOnlyHLayout")
        self.nounOnlyCheck = QtWidgets.QCheckBox(self.FastTextConfigGBox)
        self.nounOnlyCheck.setChecked(True)
        self.nounOnlyCheck.setObjectName("nounOnlyCheck")
        self.nounOnlyHLayout.addWidget(self.nounOnlyCheck)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.nounOnlyHLayout.addItem(spacerItem)
        self.verticalLayout_8.addLayout(self.nounOnlyHLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem1)
        self.configVLayout.addWidget(self.FastTextConfigGBox)
        self.createMainVLayout.addLayout(self.configVLayout)
        self.createModelBar = QtWidgets.QProgressBar(self.modelCreatorTab)
        self.createModelBar.setProperty("value", 0)
        self.createModelBar.setTextVisible(True)
        self.createModelBar.setObjectName("createModelBar")
        self.createMainVLayout.addWidget(self.createModelBar)
        self.createLogTextEdit = QtWidgets.QTextEdit(self.modelCreatorTab)
        self.createLogTextEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createLogTextEdit.sizePolicy().hasHeightForWidth())
        self.createLogTextEdit.setSizePolicy(sizePolicy)
        self.createLogTextEdit.setObjectName("createLogTextEdit")
        self.createMainVLayout.addWidget(self.createLogTextEdit)
        self.createModelBtn = QtWidgets.QPushButton(self.modelCreatorTab)
        self.createModelBtn.setObjectName("createModelBtn")
        self.createMainVLayout.addWidget(self.createModelBtn)
        self.retrainModelBtn = QtWidgets.QPushButton(self.modelCreatorTab)
        self.retrainModelBtn.setObjectName("retrainModelBtn")
        self.createMainVLayout.addWidget(self.retrainModelBtn)
        self.verticalLayout_4.addLayout(self.createMainVLayout)
        self.tabWidget.addTab(self.modelCreatorTab, "")
        self.tSNEVisualizeTab = QtWidgets.QWidget()
        self.tSNEVisualizeTab.setObjectName("tSNEVisualizeTab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tSNEVisualizeTab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.searchVLayout = QtWidgets.QVBoxLayout()
        self.searchVLayout.setSpacing(6)
        self.searchVLayout.setObjectName("searchVLayout")
        self.selectModelGBox = QtWidgets.QGroupBox(self.tSNEVisualizeTab)
        self.selectModelGBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectModelGBox.sizePolicy().hasHeightForWidth())
        self.selectModelGBox.setSizePolicy(sizePolicy)
        self.selectModelGBox.setMinimumSize(QtCore.QSize(300, 65))
        self.selectModelGBox.setMaximumSize(QtCore.QSize(16777215, 65))
        self.selectModelGBox.setObjectName("selectModelGBox")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.selectModelGBox)
        self.verticalLayout_10.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_10.setContentsMargins(9, 8, -1, -1)
        self.verticalLayout_10.setSpacing(6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.selectModelHLayout = QtWidgets.QHBoxLayout()
        self.selectModelHLayout.setObjectName("selectModelHLayout")
        self.selectModelField = QtWidgets.QLineEdit(self.selectModelGBox)
        self.selectModelField.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectModelField.sizePolicy().hasHeightForWidth())
        self.selectModelField.setSizePolicy(sizePolicy)
        self.selectModelField.setMinimumSize(QtCore.QSize(0, 0))
        self.selectModelField.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.selectModelField.setReadOnly(True)
        self.selectModelField.setObjectName("selectModelField")
        self.selectModelHLayout.addWidget(self.selectModelField)
        self.selectModelBtn = QtWidgets.QPushButton(self.selectModelGBox)
        self.selectModelBtn.setObjectName("selectModelBtn")
        self.selectModelHLayout.addWidget(self.selectModelBtn)
        self.verticalLayout_10.addLayout(self.selectModelHLayout)
        self.searchVLayout.addWidget(self.selectModelGBox)
        self.visualizeBtn = QtWidgets.QPushButton(self.tSNEVisualizeTab)
        self.visualizeBtn.setObjectName("visualizeBtn")
        self.searchVLayout.addWidget(self.visualizeBtn)
        self.plotVLayout = QtWidgets.QVBoxLayout()
        self.plotVLayout.setObjectName("plotVLayout")
        self.plotWidget = QtWidgets.QWidget(self.tSNEVisualizeTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotWidget.sizePolicy().hasHeightForWidth())
        self.plotWidget.setSizePolicy(sizePolicy)
        self.plotWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.plotWidget.setObjectName("plotWidget")
        self.mplvl = QtWidgets.QVBoxLayout(self.plotWidget)
        self.mplvl.setContentsMargins(2, 2, 2, 2)
        self.mplvl.setSpacing(2)
        self.mplvl.setObjectName("mplvl")
        self.plotVLayout.addWidget(self.plotWidget)
        self.searchVLayout.addLayout(self.plotVLayout)
        self.searchQueryGBox = QtWidgets.QGroupBox(self.tSNEVisualizeTab)
        self.searchQueryGBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchQueryGBox.sizePolicy().hasHeightForWidth())
        self.searchQueryGBox.setSizePolicy(sizePolicy)
        self.searchQueryGBox.setMinimumSize(QtCore.QSize(300, 65))
        self.searchQueryGBox.setMaximumSize(QtCore.QSize(16777215, 65))
        self.searchQueryGBox.setObjectName("searchQueryGBox")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.searchQueryGBox)
        self.verticalLayout_9.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_9.setContentsMargins(9, 8, -1, -1)
        self.verticalLayout_9.setSpacing(6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.searchQueryHLayout = QtWidgets.QHBoxLayout()
        self.searchQueryHLayout.setObjectName("searchQueryHLayout")
        self.searchQueryField = QtWidgets.QLineEdit(self.searchQueryGBox)
        self.searchQueryField.setObjectName("searchQueryField")
        self.searchQueryHLayout.addWidget(self.searchQueryField)
        self.searchQueryBtn = QtWidgets.QPushButton(self.searchQueryGBox)
        self.searchQueryBtn.setObjectName("searchQueryBtn")
        self.searchQueryHLayout.addWidget(self.searchQueryBtn)
        self.verticalLayout_9.addLayout(self.searchQueryHLayout)
        self.searchVLayout.addWidget(self.searchQueryGBox)
        self.visualizeLogTextEdit = QtWidgets.QTextEdit(self.tSNEVisualizeTab)
        self.visualizeLogTextEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visualizeLogTextEdit.sizePolicy().hasHeightForWidth())
        self.visualizeLogTextEdit.setSizePolicy(sizePolicy)
        self.visualizeLogTextEdit.setMaximumSize(QtCore.QSize(16777215, 150))
        self.visualizeLogTextEdit.setObjectName("visualizeLogTextEdit")
        self.searchVLayout.addWidget(self.visualizeLogTextEdit)
        self.verticalLayout_5.addLayout(self.searchVLayout)
        self.tabWidget.addTab(self.tSNEVisualizeTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(FastTextDialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(FastTextDialog)
        FastTextDialog.setTabOrder(self.filePathField, self.wordFrequencyField)
        FastTextDialog.setTabOrder(self.wordFrequencyField, self.vectorSizeField)
        FastTextDialog.setTabOrder(self.vectorSizeField, self.trainingSpeedField)
        FastTextDialog.setTabOrder(self.trainingSpeedField, self.windowField)
        FastTextDialog.setTabOrder(self.windowField, self.epochNumberField)
        FastTextDialog.setTabOrder(self.epochNumberField, self.nounOnlyCheck)
        FastTextDialog.setTabOrder(self.nounOnlyCheck, self.createLogTextEdit)
        FastTextDialog.setTabOrder(self.createLogTextEdit, self.createModelBtn)
        FastTextDialog.setTabOrder(self.createModelBtn, self.tabWidget)
        FastTextDialog.setTabOrder(self.tabWidget, self.selectModelField)
        FastTextDialog.setTabOrder(self.selectModelField, self.selectModelBtn)
        FastTextDialog.setTabOrder(self.selectModelBtn, self.visualizeBtn)
        FastTextDialog.setTabOrder(self.visualizeBtn, self.searchQueryField)
        FastTextDialog.setTabOrder(self.searchQueryField, self.searchQueryBtn)
        FastTextDialog.setTabOrder(self.searchQueryBtn, self.visualizeLogTextEdit)

    def retranslateUi(self, FastTextDialog):
        _translate = QtCore.QCoreApplication.translate
        FastTextDialog.setWindowTitle(_translate("FastTextDialog", "Алгоритм FastText"))
        self.FastTextConfigGBox.setTitle(_translate("FastTextDialog", "Параметры модели"))
        self.selectAnotherPathBtn.setText(_translate("FastTextDialog", "Изменить"))
        self.filePathLbl.setText(_translate("FastTextDialog", "Текстовый файл с входными данными (input file)"))
        self.filePathField.setText(_translate("FastTextDialog", "input_files/FastText"))
        self.wordFrequencyLbl.setText(_translate("FastTextDialog", "Минимальное пороговое количество повторений слова (min_count)"))
        self.vectorSizeLbl.setText(_translate("FastTextDialog", "Размерность вектора слова (size)"))
        self.trainingSpeedLbl.setText(_translate("FastTextDialog", "Коэффициент скорости обучения (learning rate)"))
        self.windowLbl.setText(_translate("FastTextDialog", "Размер окна (window)"))
        self.epochNumberLbl.setText(_translate("FastTextDialog", "Количество эпох (epoch)"))
        self.nounOnlyCheck.setText(_translate("FastTextDialog", "Только существительные"))
        self.createModelBar.setFormat(_translate("FastTextDialog", "%p%"))
        self.createModelBtn.setText(_translate("FastTextDialog", "Создать модель"))
        self.retrainModelBtn.setText(_translate("FastTextDialog", "Переобучить модель"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.modelCreatorTab), _translate("FastTextDialog", "Создание модели"))
        self.selectModelGBox.setTitle(_translate("FastTextDialog", "Загрузить модель"))
        self.selectModelField.setText(_translate("FastTextDialog", "..."))
        self.selectModelBtn.setText(_translate("FastTextDialog", "Выбрать модель"))
        self.visualizeBtn.setText(_translate("FastTextDialog", "Визуализировать"))
        self.searchQueryGBox.setTitle(_translate("FastTextDialog", "Поиск слова"))
        self.searchQueryBtn.setText(_translate("FastTextDialog", "Найти"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tSNEVisualizeTab), _translate("FastTextDialog", "Визуализация и анализ"))
