# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialogFastText.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FastTextDialog(object):
    def setupUi(self, FastTextDialog):
        FastTextDialog.setObjectName("FastTextDialog")
        FastTextDialog.resize(1119, 679)
        self.gridLayout = QtWidgets.QGridLayout(FastTextDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.main = QtWidgets.QTabWidget(FastTextDialog)
        self.main.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.main.setFont(font)
        self.main.setObjectName("main")
        self.modelCreatorTab = QtWidgets.QWidget()
        self.modelCreatorTab.setObjectName("modelCreatorTab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.modelCreatorTab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.configVLayout = QtWidgets.QVBoxLayout()
        self.configVLayout.setObjectName("configVLayout")
        self.FastTextConfigGBox = QtWidgets.QGroupBox(self.modelCreatorTab)
        self.FastTextConfigGBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FastTextConfigGBox.sizePolicy().hasHeightForWidth())
        self.FastTextConfigGBox.setSizePolicy(sizePolicy)
        self.FastTextConfigGBox.setMinimumSize(QtCore.QSize(450, 100))
        self.FastTextConfigGBox.setObjectName("FastTextConfigGBox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.FastTextConfigGBox)
        self.verticalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_8.setContentsMargins(9, 8, -1, -1)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gensimCheckbox = QtWidgets.QCheckBox(self.FastTextConfigGBox)
        self.gensimCheckbox.setMinimumSize(QtCore.QSize(0, 30))
        self.gensimCheckbox.setObjectName("gensimCheckbox")
        self.verticalLayout_8.addWidget(self.gensimCheckbox)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.selectAnotherPathBtn = QtWidgets.QPushButton(self.FastTextConfigGBox)
        self.selectAnotherPathBtn.setEnabled(True)
        self.selectAnotherPathBtn.setMinimumSize(QtCore.QSize(0, 20))
        self.selectAnotherPathBtn.setObjectName("selectAnotherPathBtn")
        self.horizontalLayout_3.addWidget(self.selectAnotherPathBtn)
        self.filePathLbl = QtWidgets.QLabel(self.FastTextConfigGBox)
        self.filePathLbl.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filePathLbl.sizePolicy().hasHeightForWidth())
        self.filePathLbl.setSizePolicy(sizePolicy)
        self.filePathLbl.setMinimumSize(QtCore.QSize(0, 30))
        self.filePathLbl.setObjectName("filePathLbl")
        self.horizontalLayout_3.addWidget(self.filePathLbl)
        self.filePathField = QtWidgets.QLineEdit(self.FastTextConfigGBox)
        self.filePathField.setEnabled(False)
        self.filePathField.setMinimumSize(QtCore.QSize(0, 20))
        self.filePathField.setObjectName("filePathField")
        self.horizontalLayout_3.addWidget(self.filePathField)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.wordFrequencyHLayout = QtWidgets.QHBoxLayout()
        self.wordFrequencyHLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.wordFrequencyHLayout.setObjectName("wordFrequencyHLayout")
        self.wordFrequencyLbl = QtWidgets.QLabel(self.FastTextConfigGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wordFrequencyLbl.sizePolicy().hasHeightForWidth())
        self.wordFrequencyLbl.setSizePolicy(sizePolicy)
        self.wordFrequencyLbl.setMinimumSize(QtCore.QSize(0, 20))
        self.wordFrequencyLbl.setObjectName("wordFrequencyLbl")
        self.wordFrequencyHLayout.addWidget(self.wordFrequencyLbl)
        self.wordFrequencyField = QtWidgets.QSpinBox(self.FastTextConfigGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wordFrequencyField.sizePolicy().hasHeightForWidth())
        self.wordFrequencyField.setSizePolicy(sizePolicy)
        self.wordFrequencyField.setMaximumSize(QtCore.QSize(110, 16777215))
        self.wordFrequencyField.setMinimum(1)
        self.wordFrequencyField.setMaximum(150)
        self.wordFrequencyField.setProperty("value", 5)
        self.wordFrequencyField.setObjectName("wordFrequencyField")
        self.wordFrequencyHLayout.addWidget(self.wordFrequencyField)
        self.verticalLayout_8.addLayout(self.wordFrequencyHLayout)
        self.vectorSizeHLayout = QtWidgets.QHBoxLayout()
        self.vectorSizeHLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.vectorSizeHLayout.setObjectName("vectorSizeHLayout")
        self.vectorSizeLbl = QtWidgets.QLabel(self.FastTextConfigGBox)
        self.vectorSizeLbl.setMinimumSize(QtCore.QSize(0, 20))
        self.vectorSizeLbl.setObjectName("vectorSizeLbl")
        self.vectorSizeHLayout.addWidget(self.vectorSizeLbl)
        self.vectorSizeField = QtWidgets.QSpinBox(self.FastTextConfigGBox)
        self.vectorSizeField.setMaximumSize(QtCore.QSize(110, 16777215))
        self.vectorSizeField.setMinimum(1)
        self.vectorSizeField.setMaximum(100000)
        self.vectorSizeField.setProperty("value", 100)
        self.vectorSizeField.setObjectName("vectorSizeField")
        self.vectorSizeHLayout.addWidget(self.vectorSizeField)
        self.verticalLayout_8.addLayout(self.vectorSizeHLayout)
        self.trainingSpeedHLayout = QtWidgets.QHBoxLayout()
        self.trainingSpeedHLayout.setObjectName("trainingSpeedHLayout")
        self.trainingSpeedLbl = QtWidgets.QLabel(self.FastTextConfigGBox)
        self.trainingSpeedLbl.setMinimumSize(QtCore.QSize(0, 20))
        self.trainingSpeedLbl.setObjectName("trainingSpeedLbl")
        self.trainingSpeedHLayout.addWidget(self.trainingSpeedLbl)
        self.trainingSpeedField = QtWidgets.QDoubleSpinBox(self.FastTextConfigGBox)
        self.trainingSpeedField.setMaximumSize(QtCore.QSize(110, 16777215))
        self.trainingSpeedField.setDecimals(3)
        self.trainingSpeedField.setMinimum(0.001)
        self.trainingSpeedField.setMaximum(1.0)
        self.trainingSpeedField.setSingleStep(0.005)
        self.trainingSpeedField.setProperty("value", 0.025)
        self.trainingSpeedField.setObjectName("trainingSpeedField")
        self.trainingSpeedHLayout.addWidget(self.trainingSpeedField)
        self.verticalLayout_8.addLayout(self.trainingSpeedHLayout)
        self.windowHLayout = QtWidgets.QHBoxLayout()
        self.windowHLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.windowHLayout.setObjectName("windowHLayout")
        self.windowLbl = QtWidgets.QLabel(self.FastTextConfigGBox)
        self.windowLbl.setMinimumSize(QtCore.QSize(155, 20))
        self.windowLbl.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.windowLbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.windowLbl.setObjectName("windowLbl")
        self.windowHLayout.addWidget(self.windowLbl)
        self.windowField = QtWidgets.QSpinBox(self.FastTextConfigGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.windowField.sizePolicy().hasHeightForWidth())
        self.windowField.setSizePolicy(sizePolicy)
        self.windowField.setMaximumSize(QtCore.QSize(110, 16777215))
        self.windowField.setMinimum(1)
        self.windowField.setMaximum(150)
        self.windowField.setProperty("value", 5)
        self.windowField.setObjectName("windowField")
        self.windowHLayout.addWidget(self.windowField)
        self.verticalLayout_8.addLayout(self.windowHLayout)
        self.epochNumberHLayout = QtWidgets.QHBoxLayout()
        self.epochNumberHLayout.setObjectName("epochNumberHLayout")
        self.epochNumberLbl = QtWidgets.QLabel(self.FastTextConfigGBox)
        self.epochNumberLbl.setMinimumSize(QtCore.QSize(0, 20))
        self.epochNumberLbl.setObjectName("epochNumberLbl")
        self.epochNumberHLayout.addWidget(self.epochNumberLbl)
        self.epochNumberField = QtWidgets.QSpinBox(self.FastTextConfigGBox)
        self.epochNumberField.setMaximumSize(QtCore.QSize(110, 16777215))
        self.epochNumberField.setMinimum(1)
        self.epochNumberField.setMaximum(1000)
        self.epochNumberField.setProperty("value", 5)
        self.epochNumberField.setObjectName("epochNumberField")
        self.epochNumberHLayout.addWidget(self.epochNumberField)
        self.verticalLayout_8.addLayout(self.epochNumberHLayout)
        self.nounOnlyHLayout = QtWidgets.QHBoxLayout()
        self.nounOnlyHLayout.setObjectName("nounOnlyHLayout")
        self.nounOnlyCheck = QtWidgets.QCheckBox(self.FastTextConfigGBox)
        self.nounOnlyCheck.setMinimumSize(QtCore.QSize(0, 20))
        self.nounOnlyCheck.setChecked(True)
        self.nounOnlyCheck.setObjectName("nounOnlyCheck")
        self.nounOnlyHLayout.addWidget(self.nounOnlyCheck)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.nounOnlyHLayout.addItem(spacerItem)
        self.verticalLayout_8.addLayout(self.nounOnlyHLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem1)
        self.configVLayout.addWidget(self.FastTextConfigGBox)
        self.createModelBar = QtWidgets.QProgressBar(self.modelCreatorTab)
        self.createModelBar.setMinimumSize(QtCore.QSize(0, 30))
        self.createModelBar.setProperty("value", 0)
        self.createModelBar.setTextVisible(True)
        self.createModelBar.setObjectName("createModelBar")
        self.configVLayout.addWidget(self.createModelBar)
        self.createModelBtn = QtWidgets.QPushButton(self.modelCreatorTab)
        self.createModelBtn.setMinimumSize(QtCore.QSize(0, 30))
        self.createModelBtn.setObjectName("createModelBtn")
        self.configVLayout.addWidget(self.createModelBtn)
        self.retrainModelBtn = QtWidgets.QPushButton(self.modelCreatorTab)
        self.retrainModelBtn.setObjectName("retrainModelBtn")
        self.configVLayout.addWidget(self.retrainModelBtn)
        self.horizontalLayout_14.addLayout(self.configVLayout)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.createLogTextEdit = QtWidgets.QTextEdit(self.modelCreatorTab)
        self.createLogTextEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createLogTextEdit.sizePolicy().hasHeightForWidth())
        self.createLogTextEdit.setSizePolicy(sizePolicy)
        self.createLogTextEdit.setMinimumSize(QtCore.QSize(400, 0))
        self.createLogTextEdit.setToolTip("")
        self.createLogTextEdit.setObjectName("createLogTextEdit")
        self.verticalLayout_15.addWidget(self.createLogTextEdit)
        self.horizontalLayout_14.addLayout(self.verticalLayout_15)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        self.main.addTab(self.modelCreatorTab, "")
        self.tSNEVisualizeTab = QtWidgets.QWidget()
        self.tSNEVisualizeTab.setObjectName("tSNEVisualizeTab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tSNEVisualizeTab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.selectModelGBox = QtWidgets.QGroupBox(self.tSNEVisualizeTab)
        self.selectModelGBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectModelGBox.sizePolicy().hasHeightForWidth())
        self.selectModelGBox.setSizePolicy(sizePolicy)
        self.selectModelGBox.setMinimumSize(QtCore.QSize(300, 130))
        self.selectModelGBox.setMaximumSize(QtCore.QSize(16777215, 130))
        self.selectModelGBox.setObjectName("selectModelGBox")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.selectModelGBox)
        self.verticalLayout_10.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_10.setContentsMargins(9, 8, -1, -1)
        self.verticalLayout_10.setSpacing(6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.selectModelHLayout = QtWidgets.QHBoxLayout()
        self.selectModelHLayout.setObjectName("selectModelHLayout")
        self.selectModelField = QtWidgets.QLineEdit(self.selectModelGBox)
        self.selectModelField.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectModelField.sizePolicy().hasHeightForWidth())
        self.selectModelField.setSizePolicy(sizePolicy)
        self.selectModelField.setMinimumSize(QtCore.QSize(0, 20))
        self.selectModelField.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.selectModelField.setReadOnly(True)
        self.selectModelField.setObjectName("selectModelField")
        self.selectModelHLayout.addWidget(self.selectModelField)
        self.selectModelBtn = QtWidgets.QPushButton(self.selectModelGBox)
        self.selectModelBtn.setMinimumSize(QtCore.QSize(0, 30))
        self.selectModelBtn.setObjectName("selectModelBtn")
        self.selectModelHLayout.addWidget(self.selectModelBtn)
        self.verticalLayout_10.addLayout(self.selectModelHLayout)
        self.label_6 = QtWidgets.QLabel(self.selectModelGBox)
        self.label_6.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_10.addWidget(self.label_6)
        self.verticalLayout_11.addWidget(self.selectModelGBox)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.visualizeBtn = QtWidgets.QPushButton(self.tSNEVisualizeTab)
        self.visualizeBtn.setObjectName("visualizeBtn")
        self.horizontalLayout_7.addWidget(self.visualizeBtn)
        self.clearPlotWidgetBtn = QtWidgets.QPushButton(self.tSNEVisualizeTab)
        self.clearPlotWidgetBtn.setObjectName("clearPlotWidgetBtn")
        self.horizontalLayout_7.addWidget(self.clearPlotWidgetBtn)
        self.verticalLayout_11.addLayout(self.horizontalLayout_7)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem2)
        self.plotWidget = QtWidgets.QWidget(self.tSNEVisualizeTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotWidget.sizePolicy().hasHeightForWidth())
        self.plotWidget.setSizePolicy(sizePolicy)
        self.plotWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.plotWidget.setObjectName("plotWidget")
        self.mplvl = QtWidgets.QVBoxLayout(self.plotWidget)
        self.mplvl.setContentsMargins(2, 2, 2, 2)
        self.mplvl.setSpacing(2)
        self.mplvl.setObjectName("mplvl")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setSpacing(6)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.plotVLayout = QtWidgets.QVBoxLayout()
        self.plotVLayout.setObjectName("plotVLayout")
        self.horizontalLayout_15.addLayout(self.plotVLayout)
        self.mplvl.addLayout(self.horizontalLayout_15)
        self.verticalLayout_11.addWidget(self.plotWidget)
        self.horizontalLayout_16.addLayout(self.verticalLayout_11)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(10, -1, -1, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.searchQueryGBox = QtWidgets.QGroupBox(self.tSNEVisualizeTab)
        self.searchQueryGBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchQueryGBox.sizePolicy().hasHeightForWidth())
        self.searchQueryGBox.setSizePolicy(sizePolicy)
        self.searchQueryGBox.setMinimumSize(QtCore.QSize(300, 100))
        self.searchQueryGBox.setMaximumSize(QtCore.QSize(16777215, 65))
        self.searchQueryGBox.setObjectName("searchQueryGBox")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.searchQueryGBox)
        self.verticalLayout_9.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_9.setContentsMargins(9, 8, -1, -1)
        self.verticalLayout_9.setSpacing(6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.searchQueryHLayout = QtWidgets.QHBoxLayout()
        self.searchQueryHLayout.setObjectName("searchQueryHLayout")
        self.searchQueryField = QtWidgets.QLineEdit(self.searchQueryGBox)
        self.searchQueryField.setObjectName("searchQueryField")
        self.searchQueryHLayout.addWidget(self.searchQueryField)
        self.searchQueryBtn = QtWidgets.QPushButton(self.searchQueryGBox)
        self.searchQueryBtn.setObjectName("searchQueryBtn")
        self.searchQueryHLayout.addWidget(self.searchQueryBtn)
        self.verticalLayout_9.addLayout(self.searchQueryHLayout)
        self.verticalLayout_6.addWidget(self.searchQueryGBox)
        self.visualizeLogTextEdit = QtWidgets.QTextEdit(self.tSNEVisualizeTab)
        self.visualizeLogTextEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visualizeLogTextEdit.sizePolicy().hasHeightForWidth())
        self.visualizeLogTextEdit.setSizePolicy(sizePolicy)
        self.visualizeLogTextEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.visualizeLogTextEdit.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.visualizeLogTextEdit.setObjectName("visualizeLogTextEdit")
        self.verticalLayout_6.addWidget(self.visualizeLogTextEdit)
        self.horizontalLayout_16.addLayout(self.verticalLayout_6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_16)
        self.main.addTab(self.tSNEVisualizeTab, "")
        self.classificationTab = QtWidgets.QWidget()
        self.classificationTab.setEnabled(True)
        self.classificationTab.setObjectName("classificationTab")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.classificationTab)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.verticalGroupBox = QtWidgets.QGroupBox(self.classificationTab)
        self.verticalGroupBox.setObjectName("verticalGroupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalGroupBox)
        self.verticalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.selectClassifierTrainFilesBtn = QtWidgets.QPushButton(self.verticalGroupBox)
        self.selectClassifierTrainFilesBtn.setObjectName("selectClassifierTrainFilesBtn")
        self.horizontalLayout_2.addWidget(self.selectClassifierTrainFilesBtn)
        self.selectClassifierFilesLbl = QtWidgets.QLabel(self.verticalGroupBox)
        self.selectClassifierFilesLbl.setObjectName("selectClassifierFilesLbl")
        self.horizontalLayout_2.addWidget(self.selectClassifierFilesLbl)
        self.selectClissifierTrainFilesField = QtWidgets.QLineEdit(self.verticalGroupBox)
        self.selectClissifierTrainFilesField.setEnabled(False)
        self.selectClissifierTrainFilesField.setObjectName("selectClissifierTrainFilesField")
        self.horizontalLayout_2.addWidget(self.selectClissifierTrainFilesField)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.label_7 = QtWidgets.QLabel(self.verticalGroupBox)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_7.setFont(font)
        self.label_7.setTextFormat(QtCore.Qt.AutoText)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.trainClissifierBtn = QtWidgets.QPushButton(self.verticalGroupBox)
        self.trainClissifierBtn.setObjectName("trainClissifierBtn")
        self.verticalLayout_3.addWidget(self.trainClissifierBtn)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_5 = QtWidgets.QLabel(self.verticalGroupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_13.addWidget(self.label_5)
        self.classifyWordFrequencyField = QtWidgets.QSpinBox(self.verticalGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.classifyWordFrequencyField.sizePolicy().hasHeightForWidth())
        self.classifyWordFrequencyField.setSizePolicy(sizePolicy)
        self.classifyWordFrequencyField.setMaximumSize(QtCore.QSize(110, 16777215))
        self.classifyWordFrequencyField.setMinimum(1)
        self.classifyWordFrequencyField.setMaximum(150)
        self.classifyWordFrequencyField.setProperty("value", 5)
        self.classifyWordFrequencyField.setObjectName("classifyWordFrequencyField")
        self.horizontalLayout_13.addWidget(self.classifyWordFrequencyField)
        self.verticalLayout_7.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_4 = QtWidgets.QLabel(self.verticalGroupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_12.addWidget(self.label_4)
        self.classifyVectorSizeField = QtWidgets.QSpinBox(self.verticalGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.classifyVectorSizeField.sizePolicy().hasHeightForWidth())
        self.classifyVectorSizeField.setSizePolicy(sizePolicy)
        self.classifyVectorSizeField.setMaximumSize(QtCore.QSize(110, 16777215))
        self.classifyVectorSizeField.setMinimum(1)
        self.classifyVectorSizeField.setMaximum(1000)
        self.classifyVectorSizeField.setProperty("value", 100)
        self.classifyVectorSizeField.setObjectName("classifyVectorSizeField")
        self.horizontalLayout_12.addWidget(self.classifyVectorSizeField)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_3 = QtWidgets.QLabel(self.verticalGroupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_11.addWidget(self.label_3)
        self.classifyTrainingSpeedField = QtWidgets.QDoubleSpinBox(self.verticalGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.classifyTrainingSpeedField.sizePolicy().hasHeightForWidth())
        self.classifyTrainingSpeedField.setSizePolicy(sizePolicy)
        self.classifyTrainingSpeedField.setMaximumSize(QtCore.QSize(110, 16777215))
        self.classifyTrainingSpeedField.setDecimals(3)
        self.classifyTrainingSpeedField.setMinimum(0.001)
        self.classifyTrainingSpeedField.setMaximum(1.0)
        self.classifyTrainingSpeedField.setSingleStep(0.005)
        self.classifyTrainingSpeedField.setProperty("value", 0.025)
        self.classifyTrainingSpeedField.setObjectName("classifyTrainingSpeedField")
        self.horizontalLayout_11.addWidget(self.classifyTrainingSpeedField)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_2 = QtWidgets.QLabel(self.verticalGroupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_10.addWidget(self.label_2)
        self.classifyWindowField = QtWidgets.QSpinBox(self.verticalGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.classifyWindowField.sizePolicy().hasHeightForWidth())
        self.classifyWindowField.setSizePolicy(sizePolicy)
        self.classifyWindowField.setMaximumSize(QtCore.QSize(110, 16777215))
        self.classifyWindowField.setMaximum(150)
        self.classifyWindowField.setProperty("value", 5)
        self.classifyWindowField.setObjectName("classifyWindowField")
        self.horizontalLayout_10.addWidget(self.classifyWindowField)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label = QtWidgets.QLabel(self.verticalGroupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_9.addWidget(self.label)
        self.classifyEpochNumberField = QtWidgets.QSpinBox(self.verticalGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.classifyEpochNumberField.sizePolicy().hasHeightForWidth())
        self.classifyEpochNumberField.setSizePolicy(sizePolicy)
        self.classifyEpochNumberField.setMaximumSize(QtCore.QSize(110, 16777215))
        self.classifyEpochNumberField.setMaximum(1000)
        self.classifyEpochNumberField.setProperty("value", 5)
        self.classifyEpochNumberField.setObjectName("classifyEpochNumberField")
        self.horizontalLayout_9.addWidget(self.classifyEpochNumberField)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.classifyNounOnlyCheck = QtWidgets.QCheckBox(self.verticalGroupBox)
        self.classifyNounOnlyCheck.setObjectName("classifyNounOnlyCheck")
        self.horizontalLayout_4.addWidget(self.classifyNounOnlyCheck)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addLayout(self.verticalLayout_7)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.selectAnotherClassificationFileBtn = QtWidgets.QPushButton(self.verticalGroupBox)
        self.selectAnotherClassificationFileBtn.setObjectName("selectAnotherClassificationFileBtn")
        self.horizontalLayout.addWidget(self.selectAnotherClassificationFileBtn)
        self.classificationFileLbl = QtWidgets.QLabel(self.verticalGroupBox)
        self.classificationFileLbl.setObjectName("classificationFileLbl")
        self.horizontalLayout.addWidget(self.classificationFileLbl)
        self.classificationFilePathField = QtWidgets.QLineEdit(self.verticalGroupBox)
        self.classificationFilePathField.setEnabled(False)
        self.classificationFilePathField.setObjectName("classificationFilePathField")
        self.horizontalLayout.addWidget(self.classificationFilePathField)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.classifyButton = QtWidgets.QPushButton(self.verticalGroupBox)
        self.classifyButton.setEnabled(True)
        self.classifyButton.setObjectName("classifyButton")
        self.verticalLayout_3.addWidget(self.classifyButton)
        self.horizontalLayout_19.addWidget(self.verticalGroupBox)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.phraseClassificationGBox = QtWidgets.QGroupBox(self.classificationTab)
        self.phraseClassificationGBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phraseClassificationGBox.sizePolicy().hasHeightForWidth())
        self.phraseClassificationGBox.setSizePolicy(sizePolicy)
        self.phraseClassificationGBox.setMinimumSize(QtCore.QSize(300, 100))
        self.phraseClassificationGBox.setMaximumSize(QtCore.QSize(16777215, 65))
        self.phraseClassificationGBox.setObjectName("phraseClassificationGBox")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.phraseClassificationGBox)
        self.verticalLayout_12.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_12.setContentsMargins(9, 8, -1, -1)
        self.verticalLayout_12.setSpacing(6)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.phraseClassificationHLayout = QtWidgets.QHBoxLayout()
        self.phraseClassificationHLayout.setObjectName("phraseClassificationHLayout")
        self.phraseClassificationField = QtWidgets.QLineEdit(self.phraseClassificationGBox)
        self.phraseClassificationField.setObjectName("phraseClassificationField")
        self.phraseClassificationHLayout.addWidget(self.phraseClassificationField)
        self.phraseClassificationBtn = QtWidgets.QPushButton(self.phraseClassificationGBox)
        self.phraseClassificationBtn.setEnabled(True)
        self.phraseClassificationBtn.setObjectName("phraseClassificationBtn")
        self.phraseClassificationHLayout.addWidget(self.phraseClassificationBtn)
        self.verticalLayout_12.addLayout(self.phraseClassificationHLayout)
        self.verticalLayout_14.addWidget(self.phraseClassificationGBox)
        self.classificationLogTextEdit = QtWidgets.QTextEdit(self.classificationTab)
        self.classificationLogTextEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.classificationLogTextEdit.sizePolicy().hasHeightForWidth())
        self.classificationLogTextEdit.setSizePolicy(sizePolicy)
        self.classificationLogTextEdit.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.classificationLogTextEdit.setObjectName("classificationLogTextEdit")
        self.verticalLayout_14.addWidget(self.classificationLogTextEdit)
        self.horizontalLayout_19.addLayout(self.verticalLayout_14)
        self.horizontalLayout_20.addLayout(self.horizontalLayout_19)
        self.main.addTab(self.classificationTab, "")
        self.verticalLayout.addWidget(self.main)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(FastTextDialog)
        self.main.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FastTextDialog)
        FastTextDialog.setTabOrder(self.wordFrequencyField, self.vectorSizeField)
        FastTextDialog.setTabOrder(self.vectorSizeField, self.trainingSpeedField)
        FastTextDialog.setTabOrder(self.trainingSpeedField, self.windowField)
        FastTextDialog.setTabOrder(self.windowField, self.epochNumberField)
        FastTextDialog.setTabOrder(self.epochNumberField, self.nounOnlyCheck)
        FastTextDialog.setTabOrder(self.nounOnlyCheck, self.selectModelField)
        FastTextDialog.setTabOrder(self.selectModelField, self.selectModelBtn)
        FastTextDialog.setTabOrder(self.selectModelBtn, self.searchQueryField)
        FastTextDialog.setTabOrder(self.searchQueryField, self.searchQueryBtn)

    def retranslateUi(self, FastTextDialog):
        _translate = QtCore.QCoreApplication.translate
        FastTextDialog.setWindowTitle(_translate("FastTextDialog", "Алгоритм FastText"))
        self.FastTextConfigGBox.setTitle(_translate("FastTextDialog", "Параметры модели"))
        self.gensimCheckbox.setText(_translate("FastTextDialog", "Использовать модель Gensim"))
        self.selectAnotherPathBtn.setText(_translate("FastTextDialog", "Изменить"))
        self.filePathLbl.setText(_translate("FastTextDialog", "Текстовый файл с входными данными"))
        self.filePathField.setText(_translate("FastTextDialog", "input_files/FastText/..."))
        self.wordFrequencyLbl.setText(_translate("FastTextDialog", "Минимальное кол-во повторений слова (min_count)"))
        self.vectorSizeLbl.setText(_translate("FastTextDialog", "Размерность вектора слова (size)"))
        self.trainingSpeedLbl.setText(_translate("FastTextDialog", "Коэффициент скорости обучения (learning rate)"))
        self.windowLbl.setText(_translate("FastTextDialog", "Размер окна (window)"))
        self.epochNumberLbl.setText(_translate("FastTextDialog", "Количество эпох (epoch)"))
        self.nounOnlyCheck.setText(_translate("FastTextDialog", "Только существительные"))
        self.createModelBar.setFormat(_translate("FastTextDialog", "%p%"))
        self.createModelBtn.setText(_translate("FastTextDialog", "Создать модель"))
        self.retrainModelBtn.setText(_translate("FastTextDialog", "Переобучить модель"))
        self.main.setTabText(self.main.indexOf(self.modelCreatorTab), _translate("FastTextDialog", "Создание модели"))
        self.selectModelGBox.setTitle(_translate("FastTextDialog", "Загрузить модель"))
        self.selectModelField.setText(_translate("FastTextDialog", "..."))
        self.selectModelBtn.setText(_translate("FastTextDialog", "Выбрать модель"))
        self.label_6.setText(_translate("FastTextDialog", "*Для корректной визуализации используются модели unsupervised или созданные с помощью gensim.\n"
"Названия файлов предпочтительно на латинице."))
        self.visualizeBtn.setText(_translate("FastTextDialog", "Визуализировать"))
        self.clearPlotWidgetBtn.setText(_translate("FastTextDialog", "Очистить область"))
        self.searchQueryGBox.setTitle(_translate("FastTextDialog", "Поиск слова"))
        self.searchQueryBtn.setText(_translate("FastTextDialog", "Найти"))
        self.main.setTabText(self.main.indexOf(self.tSNEVisualizeTab), _translate("FastTextDialog", "Визуализация и анализ"))
        self.verticalGroupBox.setTitle(_translate("FastTextDialog", "Классификация"))
        self.selectClassifierTrainFilesBtn.setText(_translate("FastTextDialog", "Изменить"))
        self.selectClassifierFilesLbl.setText(_translate("FastTextDialog", "Supervised модель или файлы для тренировки*"))
        self.selectClissifierTrainFilesField.setText(_translate("FastTextDialog", "/input_files/FastText/train..."))
        self.label_7.setText(_translate("FastTextDialog", "*В кач-ве файлов для тренировки должны использоваться модель или список файлов, где название каждого файла (только латиница) должно отражать категорию, к которой относится список текстов, содержащийся в этом файле. Например, файл, содержащий тексты категории \"комедия\", должен иметь название \"comedy.txt\".\n"
"Также может использоваться подготовленный файл (название - на латинице), где каждая строка файла содержит категорию (__label__<category>) и следующий за категорией текст (пример файла: /train/trainfile__action_adventure_comedies.txt)."))
        self.trainClissifierBtn.setText(_translate("FastTextDialog", "Запустить тренировку модели"))
        self.label_5.setText(_translate("FastTextDialog", "Минимальное кол-во повторений слова (min_count)"))
        self.label_4.setText(_translate("FastTextDialog", "Размерность вестора слова (size)"))
        self.label_3.setText(_translate("FastTextDialog", "Коэффициент скорости обучения (learning_rate)"))
        self.label_2.setText(_translate("FastTextDialog", "Размер окна (window)"))
        self.label.setText(_translate("FastTextDialog", "Кол-во эпох (epoch)"))
        self.classifyNounOnlyCheck.setText(_translate("FastTextDialog", "Только существительные"))
        self.selectAnotherClassificationFileBtn.setText(_translate("FastTextDialog", "Изменить"))
        self.classificationFileLbl.setText(_translate("FastTextDialog", "Файл для классификации:"))
        self.classificationFilePathField.setText(_translate("FastTextDialog", "input_files/FastText/classification"))
        self.classifyButton.setText(_translate("FastTextDialog", "Классифицировать"))
        self.phraseClassificationGBox.setTitle(_translate("FastTextDialog", "Классификация фразы"))
        self.phraseClassificationBtn.setText(_translate("FastTextDialog", "Классифицировать"))
        self.main.setTabText(self.main.indexOf(self.classificationTab), _translate("FastTextDialog", "Классификация"))
